name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5

      - run: |
          npm ci
          npm test
          npm run build
        env:
          PUBLIC_PATH: /vue-waveform-template/

      - uses: crazy-max/ghaction-github-pages@v2.5.0
        if: success()
        with:
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
